
package com.hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://www.hello.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AliassayHello")
    @WebResult(name = "myReturn", targetNamespace = "")
    @RequestWrapper(localName = "AliassayHello", targetNamespace = "http://www.hello.com", className = "com.hello.AliassayHello")
    @ResponseWrapper(localName = "AliassayHelloResponse", targetNamespace = "http://www.hello.com", className = "com.hello.AliassayHelloResponse")
    @Action(input = "http://www.hello.com/HelloService/AliassayHelloRequest", output = "http://www.hello.com/HelloService/AliassayHelloResponse")
    public String aliassayHello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayGoodbye", targetNamespace = "http://www.hello.com", className = "com.hello.SayGoodbye")
    @ResponseWrapper(localName = "sayGoodbyeResponse", targetNamespace = "http://www.hello.com", className = "com.hello.SayGoodbyeResponse")
    @Action(input = "http://www.hello.com/HelloService/sayGoodbyeRequest", output = "http://www.hello.com/HelloService/sayGoodbyeResponse")
    public String sayGoodbye(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
